backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true



publish_mode: editorial_workflow
media_folder: "uploads"

collections:
# topics
  - label: "Topics"
    name: "topics"
    folder: "_topics"
    create: true
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Topic Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Enter the topic title."
      - label: "Brief Description about the topic"
        name: "body"
        widget: "markdown"
        required: false
# Authors 
  - label: "Authors"
    name: "authors"
    folder: "_authors"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Identifying Name"
        name: "name"
        widget: "string"
        required: true
        hint: "Use a code or name which is used to identify otherthan name.)"
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Your Fullname."
      - label: "Avatar"
        name: "avatar"
        widget: "image"
        required: false
        hint: "Your Profile picture"
      - label: "E-mail"
        name: "email"
        widget: "string"
        required: false
        hint: "Ex: john@example.com"
      - label: "Website"
        name: "web"
        widget: "string"
        required: false
        hint: "Ex: johdoe.me"
      - label: "Facebook Username"
        name: "facebook"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "Instagram Username"
        name: "instagram"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "Whatsapp Number"
        name: "whatsapp"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "Twitter Username"
        name: "twitter"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "GitHub Username"
        name: "github"
        widget: "string"
        required: false
        hint: "Ex: johndoe4"
      - label: "About You"
        name: "body"
        widget: "markdown"
        required: false
# podcasts
  - label: "Podcasts"
    name: "podcasts"
    folder: "_podcasts"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    delete: true
    editor:
      preview: false
      delete: true
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Title of the podcasts. It must be catchy and brief."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: [display_name]
        display_fields: [display_name]
        value_field: "name"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Related Topic"
        name: "topic"
        widget: "relation"
        collection: "topics"
        search_fields: [title]
        display_fields: [title]
        value_field: "title"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Upload a image related to the podcast."
      - label: "Audio file"
        name: "podcast"
        widget: "file"
        required: true
        hint: "Upload you podcast. File size below 10mb"    
      - label: "Description about podcast"
        name: "body"
        widget: "markdown"
        required: false
  # podcasts
  - label: "Videos"
    name: "videos"
    folder: "_videos"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    delete: true
    editor:
      preview: false
      delete: true
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Title of the video. It must be catchy and brief."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: [display_name]
        display_fields: [display_name]
        value_field: "name"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Related Topic"
        name: "topic"
        widget: "relation"
        collection: "topics"
        search_fields: [title]
        display_fields: [title]
        value_field: "title"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Upload a image related to the podcast."
      - label: "Video Platform"
        name: "video_platform"
        widget: "select"
        options:
          - { label: "Youtube", value: "youtube" }
          - { label: "Dailymotion", value: "dailymotion" }
      - label: "Video link"
        name: "video"
        widget: "string"
        required: true
        hint: "Enter your video link."    
      - label: "Description about podcast"
        name: "body"
        widget: "markdown"
        required: false
  - label: "Articles"
    name: "articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Content Language"
        name: "lang"
        widget: "hidden"
        default: "mal"
      - label: "Post Reference"
        name: "lang-ref"
        widget: "string"
        hint: "Input should be unique amoung the translated post."
      - label: "Language Selector"
        name: "lang_selector"
        widget: "boolean"
        default: false
        required: false
        hint: "ON to add language changing widget."
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Post Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: My First Awesome Post!"
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Use 730*400 image."
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: true
        hint: "Use portrait posters."
      - label: "Franchise"
        name: "franchise"
        widget: "relation"
        collection: "franchises"
        searchFields: [title]
        displayFields: [title]
        valueField: "name"
        required: false
        hint: "Create a author and select it."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: [display_name]
        displayFields: [display_name]
        valueField: "name"
        required: true
        hint: "Create a author and select it."
      - label: "Genre"
        name: "genre"
        widget: "relation"
        collection: "genre"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        multiple: true
        hint: "Create a genre and select it."
      - label: "Country"
        name: "country"
        widget: "relation"
        collection: "countries"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        hint: "Create a country and select it."
      - label: "Language"
        name: "language"
        widget: "relation"
        collection: "languages"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: false
        multiple: true
        hint: "Create a country and select it."
      - label: "Director"
        name: "director"
        widget: "relation"
        collection: "director"
        searchFields: [name]
        displayFields: [name]
        valueField: "name"
        required: false
        multiple: true
        hint: "Create a director and select it."
      - label: "Subtitle"
        name: "subtitle"
        widget: "list"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Ex: Malayalam"
          - label: "File Upload"
            name: "file"
            widget: "file"
            allow_multiple: false
            media_library:
              config:
                multiple: false
            required: false
        hint: "Ex. English, Malayalam"
      - label: "Duration"
        name: "duration"
        widget: "number"
        valueType: "float"
        min: 0
        required: false
        hint: "Should in minutes."
      - label: "Content Rating"
        name: "content_rating"
        widget: "select"
        options:
          - { label: "G: General Audiences", value: "G" }
          - { label: "PG: Parental Guidance Suggested", value: "PG" }
          - { label: "PG-13: Parental Strongly Cautioned", value: "PG-13" }
          - { label: "R: Restricted", value: "R" }
          - { label: "NC-17: Adults Only", value: "NC-17" }
      - label: "Movie Rating"
        name: "rating"
        widget: "number"
        valueType: "float"
        min: 0.0
        max: 10.0
        required: false
      - label: "Release Year"
        name: "year"
        widget: "number"
        valueType: "float"
        required: false
        hint: "Ex: 2020"
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Tags help to find the content in search."
      - label: "Put this on featured"
        name: "featured"
        widget: "boolean"
        required: false
        default: false
        hint: "Put featured ON to show on featured tab"
      - label: "Image Shadow"
        name: "imageshadow"
        widget: "boolean"
        required: false
        default: true
        hint: "Put image shadow ON to show post image shadow."
      - label: "Youtube Trailer code"
        name: "youtubeId"
        widget: "string"
        required: false
        hint: "Place the youtube trailer code of trailer."
      - label: "Netflix Streaming"
        name: "netflix"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie on Netflix"
      - label: "Amazon Prime Streaming"
        name: "primeVideo"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie on Amazon Prime"
      - label: "Hotstar Streaming"
        name: "hotstar"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie on Hotstar"
      - label: "Youtube Streaming"
        name: "youtube"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie on Youtube"
      - label: "Other Streaming Link"
        name: "streamNow"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie"
      - label: "Telegram file bot link"
        name: "telegram"
        widget: "string"
        required: false
        hint: "Place the telegram bot link to download the movie"
      - label: "Small Description"
        name: "description"
        widget: "text"
        required: false
        hint: "This text is used by search engines."
      - label: "Review"
        name: "body"
        widget: "markdown"